[tool.poetry]
name = "spotify-etl-aws"
version = "0.1.0"
description = ""
authors = ["danielmschaves <danielmschaves@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
boto3 = "^1.35.0"
requests = "^2.32.0"
pytest = "^8.3.0"
pydantic = "^2.9.0"
python-dotenv = "^1.0.1"
loguru = "^0.7.2"
flask = "^2.3.0"
duckdb = "^1.0.0"
dbt-duckdb = "^1.8.0"
apache-airflow = "^2.10.5"
flake8 = "^7.0.0"
chardet = "^5.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
