version: 2

models:
  - name: stg_playlists
    description: "This view represents user-created playlists, detailing each playlist's properties, ownership, and audience visibility."
    columns:
      - name: playlist_id
        description: "Primary key. Unique identifier for the playlist."
      - name: playlist_name
        description: "Name of the playlist."
      - name: playlist_description
        description: "Description of the playlist provided by its creator."
      - name: playlist_owner_id
        description: "Identifier of the user who owns the playlist."
      - name: playlist_followers
        description: "Number of followers or subscribers of the playlist."
      - name: playlist_public
        description: "Boolean flag indicating whether the playlist is public or private."

  - name: stg_tracks
    description: "Contains detailed information about each track, including links to the playlist and album it belongs to, its popularity, and specific track details."
    columns:
      - name: track_id
        description: "Primary key. Unique identifier for the track."
      - name: track_name
        description: "Name of the track."
      - name: playlist_id
        description: "Foreign key to playlists. Identifier of the playlist containing this track."
      - name: album_id
        description: "Foreign key to albums. Identifier of the album containing this track."
      - name: track_duration_ms
        description: "Duration of the track in milliseconds."
      - name: track_popularity
        description: "Popularity score of the track."
      - name: track_explicit
        description: "Boolean flag indicating whether the track has explicit content."
      - name: track_number
        description: "Track number on its album."
      - name: album_release_date
        description: "Release date of the track's album."
      - name: artist_id
        description: "Foreign key to artists. Identifier of the artist who performed the track."

  - name: stg_artists
    description: "Details about artists, including their names and the tracks they have performed."
    columns:
      - name: artist_id
        description: "Primary key. Unique identifier for the artist."
      - name: artist_name
        description: "Name of the artist."
      - name: track_id
        description: "Foreign key to tracks. Identifier of a track performed by the artist."

  - name: stg_albums
    description: "Details about albums, including their release dates, the tracks they contain, and their overall popularity."
    columns:
      - name: album_id
        description: "Primary key. Unique identifier for the album."
      - name: album_name
        description: "Name of the album."
      - name: album_release_date
        description: "Release date of the album."
      - name: album_total_tracks
        description: "Total number of tracks in the album."
      - name: album_track_id
        description: "Foreign key to artists. Identifier of the artist who released the album."
